version: '3.8'
services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:80'
    ports:
      - 80:80
    environment:
      - DEBUG=1
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=onlineserviceuser
      - POSTGRES_PASSWORD=onlineservicepassword
      - POSTGRES_DB=onlineservice
volumes:
  postgres_data: