version: '3.7'
services:
  web:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./:/usr/src/app/
    ports:
      - "80:80"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=onlineserviceuser
      - POSTGRES_PASSWORD=onlineservicepassword
      - POSTGRES_DB=onlineservice
volumes:
  postgres_data: