# Generated by Django 4.0.5 on 2022-06-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUnit',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('parentId', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField(null=True)),
                ('children', models.ManyToManyField(to='shop.shopunit')),
            ],
        ),
        migrations.DeleteModel(
            name='ShopUnitType',
        ),
    ]
