# Generated by Django 4.0.5 on 2022-06-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shopunit_total_inner_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunit',
            name='children',
            field=models.ManyToManyField(default=[], null=True, to='shop.shopunit'),
        ),
    ]
