# Generated by Django 4.0.5 on 2022-06-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_shopunit_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunit',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
