# Generated by Django 4.0.5 on 2022-06-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_shopunit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunit',
            name='date',
            field=models.CharField(max_length=40),
        ),
    ]
