# Generated by Django 4.0.5 on 2022-06-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_shopunit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUnitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_reference', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=40)),
                ('parentId', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(choices=[('CATEGORY', 'CATEGORY'), ('OFFER', 'OFFER')], max_length=100)),
                ('price', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryTable',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('history_objects', models.ManyToManyField(to='shop.shopunithistory')),
            ],
        ),
    ]
