# Generated by Django 4.0.5 on 2022-06-26 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_shopunithistory_historytable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryTable',
        ),
        migrations.DeleteModel(
            name='ShopUnitHistory',
        ),
    ]
