name: Build docker image and push to Docker Hub

on: [push]
    

jobs:

  build-and-push:
    name: Authorize, build and push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authorize
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push
      run: |
        docker build . -t goodsservice
        docker tag goodsservice ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_MOVIES_SERVICE_SERVER_REPOSITORY }}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_MOVIES_SERVICE_SERVER_REPOSITORY }} 