name: Test Django-Rest-Framework application via PyTest

on: [push]

jobs:
  runtest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run tests
      run: |
        python unit_test.py